const bcrypt = require('bcryptjs');
const { booksStore, usersStore, transactionsStore, reviewsStore, chaptersStore } = require('./services/excel');

const SAMPLE_BOOKS = [
  { title: 'To Kill a Mockingbird', author: 'Harper Lee', isbn: '978-0061120084', genre: 'Fiction', publishYear: 1960, publisher: 'J. B. Lippincott & Co.', description: 'A gripping, heart-wrenching tale of racial injustice in the Deep South, seen through the eyes of young Scout Finch.', totalCopies: 3, availableCopies: 3, rating: 4.8, ratingCount: 12, coverUrl: '' },
  { title: '1984', author: 'George Orwell', isbn: '978-0451524935', genre: 'Science Fiction', publishYear: 1949, publisher: 'Secker & Warburg', description: 'A dystopian masterpiece about totalitarianism, surveillance, and the terrifying power of propaganda.', totalCopies: 4, availableCopies: 4, rating: 4.7, ratingCount: 18, coverUrl: '' },
  { title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', isbn: '978-0743273565', genre: 'Fiction', publishYear: 1925, publisher: "Charles Scribner's Sons", description: 'A portrait of the Jazz Age and the American Dream, following the mysterious millionaire Jay Gatsby.', totalCopies: 2, availableCopies: 2, rating: 4.4, ratingCount: 9, coverUrl: '' },
  { title: 'Pride and Prejudice', author: 'Jane Austen', isbn: '978-0141439518', genre: 'Romance', publishYear: 1813, publisher: 'T. Egerton', description: 'The timeless story of Elizabeth Bennet and Mr. Darcy, exploring themes of love, class, and first impressions.', totalCopies: 3, availableCopies: 3, rating: 4.6, ratingCount: 15, coverUrl: '' },
  { title: 'The Hobbit', author: 'J.R.R. Tolkien', isbn: '978-0547928227', genre: 'Fantasy', publishYear: 1937, publisher: 'George Allen & Unwin', description: 'Bilbo Baggins embarks on an unexpected journey with a company of dwarves to reclaim their homeland.', totalCopies: 3, availableCopies: 3, rating: 4.7, ratingCount: 20, coverUrl: '' },
  { title: 'Fahrenheit 451', author: 'Ray Bradbury', isbn: '978-1451673319', genre: 'Science Fiction', publishYear: 1953, publisher: 'Ballantine Books', description: 'In a future where books are banned and firemen burn them, one man begins to question everything.', totalCopies: 2, availableCopies: 2, rating: 4.4, ratingCount: 11, coverUrl: '' },
  { title: 'Brave New World', author: 'Aldous Huxley', isbn: '978-0060850524', genre: 'Science Fiction', publishYear: 1932, publisher: 'Chatto & Windus', description: 'A chilling vision of a technologically advanced future where humans are genetically modified and socially conditioned.', totalCopies: 2, availableCopies: 2, rating: 4.3, ratingCount: 8, coverUrl: '' },
  { title: 'The Lord of the Rings', author: 'J.R.R. Tolkien', isbn: '978-0618640157', genre: 'Fantasy', publishYear: 1954, publisher: 'Allen & Unwin', description: 'The epic quest to destroy the One Ring and save Middle-earth from the Dark Lord Sauron.', totalCopies: 2, availableCopies: 2, rating: 4.9, ratingCount: 25, coverUrl: '' },
  { title: 'Jane Eyre', author: 'Charlotte Brontë', isbn: '978-0141441146', genre: 'Fiction', publishYear: 1847, publisher: 'Smith, Elder & Co.', description: 'An independent young governess falls in love with her brooding employer, discovering dark secrets at Thornfield Hall.', totalCopies: 2, availableCopies: 2, rating: 4.5, ratingCount: 10, coverUrl: '' },
  { title: 'Dune', author: 'Frank Herbert', isbn: '978-0441013593', genre: 'Science Fiction', publishYear: 1965, publisher: 'Chilton Books', description: 'On the desert planet Arrakis, young Paul Atreides must navigate politics, religion, and ecology to fulfill his destiny.', totalCopies: 3, availableCopies: 3, rating: 4.6, ratingCount: 16, coverUrl: '' },
  { title: 'The Alchemist', author: 'Paulo Coelho', isbn: '978-0062315007', genre: 'Fiction', publishYear: 1988, publisher: 'HarperOne', description: 'A shepherd boy journeys from Spain to Egypt in search of treasure, discovering the true meaning of life along the way.', totalCopies: 3, availableCopies: 3, rating: 4.2, ratingCount: 14, coverUrl: '' },
  { title: 'The Catcher in the Rye', author: 'J.D. Salinger', isbn: '978-0316769488', genre: 'Fiction', publishYear: 1951, publisher: 'Little, Brown', description: 'The story of teenage Holden Caulfield wandering New York City after being expelled from prep school.', totalCopies: 2, availableCopies: 2, rating: 4.0, ratingCount: 7, coverUrl: '' },
  { title: 'The Art of War', author: 'Sun Tzu', isbn: '978-1590302255', genre: 'Philosophy', publishYear: -500, publisher: 'Shambhala', description: 'Ancient Chinese military treatise on strategy, tactics, and the philosophy of warfare.', totalCopies: 2, availableCopies: 2, rating: 4.3, ratingCount: 6, coverUrl: '' },
  { title: 'Sapiens', author: 'Yuval Noah Harari', isbn: '978-0062316097', genre: 'Non-Fiction', publishYear: 2011, publisher: 'Harper', description: 'A sweeping history of humankind, from the Stone Age to the Silicon Age.', totalCopies: 3, availableCopies: 3, rating: 4.5, ratingCount: 19, coverUrl: '' },
  { title: 'The Midnight Library', author: 'Matt Haig', isbn: '978-0525559474', genre: 'Fiction', publishYear: 2020, publisher: 'Viking', description: 'Between life and death, Nora Seed finds a library that lets her live alternate versions of her life.', totalCopies: 4, availableCopies: 4, rating: 4.3, ratingCount: 13, coverUrl: '' },
  { title: 'Project Hail Mary', author: 'Andy Weir', isbn: '978-0593135204', genre: 'Science Fiction', publishYear: 2021, publisher: 'Ballantine Books', description: 'A lone astronaut must save Earth from an extinction-level threat, with only his wits and an unlikely ally.', totalCopies: 3, availableCopies: 3, rating: 4.8, ratingCount: 22, coverUrl: '' },
  { title: 'Educated', author: 'Tara Westover', isbn: '978-0399590504', genre: 'Biography', publishYear: 2018, publisher: 'Random House', description: 'A memoir of a woman who grew up in a survivalist family and went on to earn a PhD from Cambridge.', totalCopies: 2, availableCopies: 2, rating: 4.6, ratingCount: 11, coverUrl: '' },
  { title: 'The Name of the Wind', author: 'Patrick Rothfuss', isbn: '978-0756404741', genre: 'Fantasy', publishYear: 2007, publisher: 'DAW Books', description: 'Kvothe, a legendary figure, tells the true story of his extraordinary life from humble beginnings to infamy.', totalCopies: 2, availableCopies: 2, rating: 4.5, ratingCount: 17, coverUrl: '' },
  { title: 'Atomic Habits', author: 'James Clear', isbn: '978-0735211292', genre: 'Self-Help', publishYear: 2018, publisher: 'Avery', description: 'A practical guide to building good habits, breaking bad ones, and mastering the tiny behaviors that lead to remarkable results.', totalCopies: 4, availableCopies: 4, rating: 4.7, ratingCount: 21, coverUrl: '' },
  { title: 'The Silent Patient', author: 'Alex Michaelides', isbn: '978-1250301697', genre: 'Thriller', publishYear: 2019, publisher: 'Celadon Books', description: 'A famous painter shoots her husband and never speaks again. A psychotherapist becomes obsessed with uncovering the truth.', totalCopies: 3, availableCopies: 3, rating: 4.2, ratingCount: 10, coverUrl: '' },
];

async function seed() {
  const existingBooks = booksStore.readAll();
  if (existingBooks.length > 0) {
    console.log('  Data already seeded, skipping...');
    return;
  }

  console.log('  Seeding initial data...');

  // Seed users
  const adminPw = await bcrypt.hash('admin123', 10);
  const librarianPw = await bcrypt.hash('librarian123', 10);
  const memberPw = await bcrypt.hash('member123', 10);

  await usersStore.createMany([
    { name: 'Admin User', email: 'admin@library.com', password: adminPw, role: 'admin', provider: 'local', providerId: null, avatar: null, isActive: true, theme: 'light', lastLogin: new Date().toISOString() },
    { name: 'Sarah Librarian', email: 'librarian@library.com', password: librarianPw, role: 'librarian', provider: 'local', providerId: null, avatar: null, isActive: true, theme: 'light', lastLogin: new Date().toISOString() },
    { name: 'Alex Member', email: 'member@library.com', password: memberPw, role: 'member', provider: 'local', providerId: null, avatar: null, isActive: true, theme: 'light', lastLogin: new Date().toISOString() },
  ]);

  // Seed books
  await booksStore.createMany(SAMPLE_BOOKS.map(b => ({ ...b, addedBy: 'system' })));

  // Seed a few transactions and reviews
  const users = usersStore.readAll();
  const books = booksStore.readAll();
  const member = users.find(u => u.role === 'member');
  const librarian = users.find(u => u.role === 'librarian');

  if (member && books.length >= 3) {
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + 14);

    const pastDue = new Date();
    pastDue.setDate(pastDue.getDate() - 3);

    await transactionsStore.createMany([
      { bookId: books[0].id, userId: member.id, type: 'checkout', checkoutDate: new Date(Date.now() - 7 * 86400000).toISOString(), dueDate: dueDate.toISOString(), returnDate: null, status: 'active', notes: 'Demo checkout', processedBy: librarian?.id || 'system' },
      { bookId: books[4].id, userId: member.id, type: 'checkout', checkoutDate: new Date(Date.now() - 20 * 86400000).toISOString(), dueDate: pastDue.toISOString(), returnDate: null, status: 'active', notes: 'Overdue demo', processedBy: librarian?.id || 'system' },
      { bookId: books[1].id, userId: member.id, type: 'checkout', checkoutDate: new Date(Date.now() - 30 * 86400000).toISOString(), dueDate: new Date(Date.now() - 16 * 86400000).toISOString(), returnDate: new Date(Date.now() - 15 * 86400000).toISOString(), status: 'returned', notes: 'Returned on time', processedBy: librarian?.id || 'system' },
    ]);

    await booksStore.update(books[0].id, { availableCopies: books[0].availableCopies - 1 });
    await booksStore.update(books[4].id, { availableCopies: books[4].availableCopies - 1 });

    await reviewsStore.createMany([
      { bookId: books[1].id, userId: member.id, userName: member.name, rating: 5, comment: 'Absolutely brilliant. A must-read for everyone.' },
      { bookId: books[4].id, userId: member.id, userName: member.name, rating: 4, comment: 'A wonderful adventure story. Tolkien at his best.' },
    ]);
  }

  // Seed chapters with content for several books
  await seedChapters(books);

  console.log(`  Seeded ${SAMPLE_BOOKS.length} books, 3 users, sample transactions & chapters`);
}

async function seedChapters(books) {
  const find = title => books.find(b => b.title === title);

  const tkam = find('To Kill a Mockingbird');
  const nineteen84 = find('1984');
  const gatsby = find('The Great Gatsby');
  const hobbit = find('The Hobbit');
  const dune = find('Dune');
  const atomicHabits = find('Atomic Habits');

  const allChapters = [];

  if (tkam) {
    allChapters.push(
      { bookId: tkam.id, chapterNumber: 1, title: 'The Radley Place', summary: 'Introduction to Maycomb, the Finch family, and the mysterious Boo Radley.', content: 'When he was nearly thirteen, my brother Jem got his arm badly broken at the elbow. When enough years had gone by to enable us to look back on them, we sometimes discussed the events leading to his accident. Maycomb was an old town, but it was a tired old town when I first knew it. In rainy weather the streets turned to red slop; grass grew on the sidewalks, the courthouse sagged in the square. People moved slowly then. They ambled across the square, shuffled in and out of the stores around it, took their time about everything. A day was twenty-four hours long but seemed longer. There was no hurry, for there was nowhere to go, nothing to buy and no money to buy it with. Atticus Finch, our father, was related by blood or marriage to nearly every family in the town. Scout and Jem begin their fascination with the Radley Place, a mysterious house at the end of their street where Boo Radley lives in seclusion.', addedBy: 'system' },
      { bookId: tkam.id, chapterNumber: 2, title: 'Miss Caroline and the Cunninghams', summary: 'Scout\'s first day of school introduces class differences in Maycomb.', content: 'Dill left us early in September, to be returned to Meridian. We saw him off on the five o\'clock bus and I was miserable without him. Scout begins first grade under Miss Caroline Fisher, a young teacher from North Alabama. Miss Caroline is unfamiliar with Maycomb\'s ways. When Walter Cunningham comes to school without lunch and refuses to borrow money, Scout tries to explain the Cunningham family\'s pride and poverty. The Cunninghams are poor but honest farmers who never take what they cannot repay. Miss Caroline, unable to understand the local customs, punishes Scout for her explanations. This chapter establishes the rigid class structure of Maycomb and the different social standings of its families.', addedBy: 'system' },
      { bookId: tkam.id, chapterNumber: 3, title: 'Walter Cunningham Comes to Dinner', summary: 'Lessons about empathy as Atticus teaches Scout to understand others.', content: 'Catching Walter Cunningham in the schoolyard gave me some pleasure, but when I was rubbing his nose in the dirt Jem came by and told me to stop. Jem invites Walter home for dinner, where Scout is shocked by Walter\'s table manners — he pours syrup over all his food. Calpurnia scolds Scout for her rudeness, teaching her that anyone who is a guest in their house deserves respect. Atticus reinforces this lesson with his famous advice: "You never really understand a person until you consider things from his point of view — until you climb into his skin and walk around in it." This foundational chapter introduces the novel\'s core theme of empathy and moral education.', addedBy: 'system' },
      { bookId: tkam.id, chapterNumber: 4, title: 'The Knothole Treasures', summary: 'Scout and Jem find gifts hidden in a tree near the Radley house.', content: 'The remainder of my school days were no more auspicious than the first. Scout finds pieces of chewing gum, then Indian-head pennies, in the knothole of a live oak tree on the edge of the Radley lot. She and Jem begin a collection of treasures left in the knothole, including carved soap figurines, a broken watch, and a ball of twine. The children also invent the "Boo Radley game," acting out their imagined version of the Radley family\'s history. Atticus catches them and warns them to stop tormenting the Radleys. The gifts in the tree represent Boo\'s tentative attempts to reach out to the children, establishing the slow build toward their eventual understanding of him.', addedBy: 'system' },
    );
  }

  if (nineteen84) {
    allChapters.push(
      { bookId: nineteen84.id, chapterNumber: 1, title: 'The World of Oceania', summary: 'Winston Smith begins his secret rebellion against the Party by starting a diary.', content: 'It was a bright cold day in April, and the clocks were striking thirteen. Winston Smith, his chin nuzzled into his breast in an effort to escape the vile wind, slipped quickly through the glass doors of Victory Mansions, though not quickly enough to prevent a swirl of gritty dust from entering along with him. The hallway smelt of boiled cabbage and old rag mats. At one end of it a coloured poster, too large for indoor display, had been tacked to the wall. It depicted simply an enormous face, more than a metre wide: the face of a man of about forty-five, with a heavy black moustache and ruggedly handsome features. BIG BROTHER IS WATCHING YOU, the caption beneath it ran. Winston makes his way to his flat in Victory Mansions. The telescreen in his living room can never be turned off. He sits in an alcove out of the telescreen\'s view and begins writing in a diary — a thoughtcrime punishable by death.', addedBy: 'system' },
      { bookId: nineteen84.id, chapterNumber: 2, title: 'The Two Minutes Hate', summary: 'The Party\'s daily ritual of hatred and Winston\'s first encounter with O\'Brien.', content: 'The next moment a hideous, grinding speech, as of some monstrous machine running without oil, burst from the big telescreen at the end of the room. The Two Minutes Hate is a daily ritual where Party members watch films of Emmanuel Goldstein, the Enemy of the People, and work themselves into a frenzy of hatred. Goldstein was once a leading figure in the Party but is now its principal traitor. During the Hate, Winston catches the eye of O\'Brien, a member of the Inner Party. For a fleeting moment, Winston feels O\'Brien shares his secret opposition to the Party. He also notices a dark-haired girl from the Fiction Department staring at him. The chapter establishes the Party\'s mechanism for channeling citizens\' frustration and maintaining control through collective rage.', addedBy: 'system' },
      { bookId: nineteen84.id, chapterNumber: 3, title: 'The Ministry of Truth', summary: 'Winston\'s work altering historical records at the Ministry of Truth.', content: 'Winston\'s job at the Ministry of Truth (Minitrue in Newspeak) involves rewriting historical records so that they match the Party\'s ever-changing version of reality. When the Party changes its alliances or economic predictions, all past records must be altered to show the Party was always correct. The Ministry\'s slogan is "Who controls the past controls the future: who controls the present controls the past." Winston handles a case where a man named Withers, once a Party hero, has become an unperson. Winston must eliminate all evidence that Withers ever existed. He creates a fictional war hero, Comrade Ogilvy, to replace Withers in the records. The chapter explores the terrifying power of state-controlled information and the destruction of objective truth.', addedBy: 'system' },
      { bookId: nineteen84.id, chapterNumber: 4, title: 'Newspeak and the Proles', summary: 'The engineering of language as thought control and life among the lower classes.', content: 'Winston\'s colleague Syme is working on the Eleventh Edition of the Newspeak dictionary. Syme enthusiastically explains the purpose of Newspeak: to narrow the range of thought. "Every year fewer and fewer words, and the range of consciousness always a little smaller." If there is no word for rebellion, rebellion becomes literally unthinkable. Winston realizes that Syme, despite his orthodoxy, is too intelligent and will eventually be vaporized. Meanwhile, Winston walks through the prole districts — the working-class areas where 85% of Oceania\'s population lives in relative freedom because the Party considers them beneath notice. "If there is hope, it lies in the proles," Winston writes, though he wonders if the proles can ever become conscious of their own strength.', addedBy: 'system' },
    );
  }

  if (gatsby) {
    allChapters.push(
      { bookId: gatsby.id, chapterNumber: 1, title: 'Nick Carraway Arrives', summary: 'Nick introduces himself and his new life on Long Island next to the mysterious Gatsby.', content: 'In my younger and more vulnerable years my father gave me some advice that I\'ve been turning over in my mind ever since. "Whenever you feel like criticizing anyone," he told me, "just remember that all the people in this world haven\'t had the advantages that you\'ve had." Nick Carraway, a young Yale graduate from the Midwest, has come East to learn the bond business. He rents a small house in West Egg, Long Island, next to a lavish mansion owned by a mysterious man named Gatsby. Nick visits his cousin Daisy Buchanan and her husband Tom in East Egg. Tom is having an affair, which Daisy seems to know about. At the end of the evening, Nick returns home and sees Gatsby standing on his lawn, arms stretched toward a green light across the bay.', addedBy: 'system' },
      { bookId: gatsby.id, chapterNumber: 2, title: 'The Valley of Ashes', summary: 'Tom takes Nick to meet his mistress Myrtle Wilson in the desolate industrial wasteland.', content: 'About half way between West Egg and New York the motor road hastily joins the railroad and runs beside it for a quarter of a mile, so as to shrink away from a certain desolate area of land. This is a valley of ashes — a fantastic farm where ashes grow like wheat into ridges and hills and grotesque gardens; where ashes take the forms of houses and chimneys. Above the valley, the eyes of Doctor T. J. Eckleburg stare down from an old advertising billboard — blue and gigantic, their retinas one yard high. Tom brings Nick to George Wilson\'s garage, where Tom\'s mistress Myrtle Wilson lives with her husband. They take the train to New York for a party at the apartment Tom keeps for Myrtle. The party grows increasingly raucous. Tom breaks Myrtle\'s nose when she taunts him by repeating Daisy\'s name.', addedBy: 'system' },
      { bookId: gatsby.id, chapterNumber: 3, title: 'Gatsby\'s Party', summary: 'Nick attends one of Gatsby\'s legendary parties and finally meets the host himself.', content: 'There was music from my neighbor\'s house through the summer nights. In his blue gardens men and girls came and went like moths among the whisperings and the champagne and the stars. Nick receives a formal invitation to one of Gatsby\'s legendary parties — an unusual distinction, since most guests arrive uninvited. The party is an enormous affair with a full orchestra, cascading champagne, and hundreds of guests. Rumors about Gatsby circulate: he killed a man, he was a German spy, he\'s a bootlegger. Nick meets Jordan Baker and they wander the mansion. He finally meets Gatsby himself, not recognizing him at first. Gatsby is surprisingly young and has an affected formality. He smiles with a quality of eternal reassurance, then disappears to take a phone call from Chicago.', addedBy: 'system' },
    );
  }

  if (hobbit) {
    allChapters.push(
      { bookId: hobbit.id, chapterNumber: 1, title: 'An Unexpected Party', summary: 'Gandalf and thirteen dwarves arrive at Bilbo\'s comfortable hobbit-hole.', content: 'In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort. Bilbo Baggins lives a quiet, predictable life in Bag End under The Hill. One morning, the wizard Gandalf appears at his door and marks it with a secret sign. That evening, thirteen dwarves arrive one by one — Dwalin, Balin, Kili, Fili, Dori, Nori, Ori, Oin, Gloin, Bifur, Bofur, Bombur, and their leader Thorin Oakenshield. They eat Bilbo\'s food and sing of their quest to reclaim the Lonely Mountain and its treasure from the dragon Smaug. Gandalf produces a map showing a secret door into the mountain and names Bilbo as the company\'s burglar.', addedBy: 'system' },
      { bookId: hobbit.id, chapterNumber: 2, title: 'Roast Mutton', summary: 'The company encounters three trolls who nearly eat them before Gandalf intervenes.', content: 'Up jumped Bilbo, and putting on his dressing-gown went into the dining-room. There he saw nobody, but all the signs of a large and hurried breakfast. The company departs on ponies, and Bilbo forgets his handkerchief. As rain begins to fall, they notice Gandalf has disappeared. Bilbo spots a fire in the distance and is sent to investigate. He finds three enormous trolls — Bert, Tom, and William — roasting mutton. Bilbo tries to pick William\'s pocket but is caught. The dwarves come to investigate and are captured one by one. Gandalf returns just in time, using ventriloquism to keep the trolls arguing until dawn turns them to stone. In the trolls\' cave they find food, gold, and two Elvish swords which Thorin and Gandalf claim. Bilbo finds a small knife that serves him as a sword.', addedBy: 'system' },
      { bookId: hobbit.id, chapterNumber: 3, title: 'A Short Rest', summary: 'The company arrives at Rivendell and receives counsel from Elrond.', content: 'They did not sing or tell stories that day, even though the weather improved; nor the next day, nor the day after. The company descends into the hidden valley of Rivendell, home of Elrond Half-elven and the Last Homely House. Elrond is descended from both Elves and Men and is as noble and fair as an elf-lord, as strong as a warrior, and as wise as a wizard. He reads the moon-letters on Thorin\'s map, revealing instructions for finding the secret door: "Stand by the grey stone when the thrush knocks, and the setting sun with the last light of Durin\'s Day will shine upon the key-hole." The company rests and eats well in Rivendell, restoring their spirits before the dangerous journey through the Misty Mountains.', addedBy: 'system' },
      { bookId: hobbit.id, chapterNumber: 4, title: 'Over Hill and Under Hill', summary: 'Captured by goblins in the Misty Mountains, the company barely escapes.', content: 'There were many paths that led up into those mountains, and many passes over them. But most of the paths were cheats and deceptions and led nowhere or to bad ends; and most of the passes were infested by evil things and dreadful dangers. The company takes shelter in a cave during a thunderstorm. In the night, goblins pour from a crack in the cave wall and capture them all except Gandalf. Dragged before the Great Goblin in the heart of the mountain, they face execution. The Great Goblin recognizes Thorin\'s Elvish sword — called Orcrist, the Goblin-cleaver. Gandalf appears, slays the Great Goblin with a flash of lightning, and leads the company in a desperate escape through dark tunnels. In the chaos, Bilbo is knocked unconscious and left behind in the darkness.', addedBy: 'system' },
      { bookId: hobbit.id, chapterNumber: 5, title: 'Riddles in the Dark', summary: 'Bilbo discovers the One Ring and outwits Gollum in a deadly riddle contest.', content: 'When Bilbo opened his eyes, he wondered if he had; for it was just as dark as with them shut. No one was anywhere near him. Alone in the dark goblin tunnels, Bilbo finds a small metal ring on the ground and pockets it. He stumbles upon an underground lake where Gollum, a wretched creature, lives on a slimy island. Gollum proposes a riddle-game: if Bilbo wins, Gollum will show him the way out; if Gollum wins, he eats Bilbo. They exchange riddles back and forth — about mountains, wind, darkness, time, and fish. Finally, Bilbo asks "What have I got in my pocket?" Gollum cannot answer. Enraged, Gollum realizes his "precious" ring is missing. Bilbo accidentally discovers the ring makes him invisible and uses it to follow Gollum to the exit, slipping past goblins to rejoin the dwarves outside.', addedBy: 'system' },
    );
  }

  if (dune) {
    allChapters.push(
      { bookId: dune.id, chapterNumber: 1, title: 'The Gom Jabbar', summary: 'Paul Atreides faces the Reverend Mother\'s test of humanity with the pain box.', content: 'A beginning is the time for taking the most delicate care that the balances are correct. The Reverend Mother Gaius Helen Mohiam of the Bene Gesserit arrives on Caladan to test young Paul Atreides with the gom jabbar — a poisoned needle held at his neck while his hand is placed in a box that induces escalating pain through nerve induction. He must not withdraw his hand or die. The test determines whether a being can override instinct with reason, the mark of a human versus an animal. Paul endures pain beyond anything the Reverend Mother has seen before. She suspects he may be the Kwisatz Haderach, the superbeing the Bene Gesserit have sought to breed for centuries. Paul\'s mother Jessica, a Bene Gesserit herself, waits anxiously outside, knowing the test could kill her son.', addedBy: 'system' },
      { bookId: dune.id, chapterNumber: 2, title: 'Arrakis Awaits', summary: 'House Atreides prepares to leave Caladan for the desert planet Arrakis.', content: 'The Duke Leto Atreides is ordered by the Padishah Emperor Shaddam IV to take control of Arrakis, the only source of the spice melange — the most valuable substance in the universe. Melange extends life, expands consciousness, and is essential for space navigation. Arrakis was previously controlled by House Harkonnen, the Atreides\' ancient enemies. Leto knows the move is a trap — the Emperor fears the Atreides\' growing popularity — but he cannot refuse an imperial order. He plans to ally with the Fremen, the fierce desert people of Arrakis, to build a fighting force. Paul studies the desert world through filmbooks and learns about sandworms, stillsuits, and the harsh beauty of Arrakis. The Atreides motto is "Here I am, here I remain."', addedBy: 'system' },
      { bookId: dune.id, chapterNumber: 3, title: 'The Desert World', summary: 'The Atreides arrive on Arrakis and discover the challenges of desert survival.', content: 'Arrakis — Dune — Desert Planet. The Atreides arrive at the capital city of Arrakeen and find it a hostile environment, nothing like their ocean homeworld of Caladan. Water is the most precious resource; people wear stillsuits that reclaim body moisture. Spice mining operations are constantly threatened by enormous sandworms, some over 400 meters long, that are attracted to rhythmic vibrations. Paul and his mother explore their new home while Leto begins the dangerous political work of governing. Dr. Liet-Kynes, the imperial planetologist, introduces them to desert ecology and the secret Fremen dream of terraforming Arrakis into a green world. Paul begins experiencing prescient visions that trouble and fascinate him, seeing threads of possible futures branching outward from every decision.', addedBy: 'system' },
    );
  }

  if (atomicHabits) {
    allChapters.push(
      { bookId: atomicHabits.id, chapterNumber: 1, title: 'The Surprising Power of Atomic Habits', summary: 'Why tiny changes produce remarkable results through compound growth.', content: 'Habits are the compound interest of self-improvement. Getting 1 percent better every day counts for a lot in the long run. If you get 1 percent better each day for one year, you\'ll end up 37 times better. If you get 1 percent worse each day, you\'ll decline nearly to zero. This is the power of atomic habits: small, incremental changes that appear insignificant in the moment but deliver remarkable results over time. The problem is that progress is not linear. You often spend months or years working without visible progress, until you cross a critical threshold. James Clear calls this the "Plateau of Latent Potential." People give up because they expect progress to be linear, but breakthroughs come from the accumulation of many small actions. Your outcomes are a lagging measure of your habits.', addedBy: 'system' },
      { bookId: atomicHabits.id, chapterNumber: 2, title: 'How Your Habits Shape Your Identity', summary: 'The three layers of behavior change and the importance of identity-based habits.', content: 'There are three layers of behavior change: outcomes, processes, and identity. Outcomes are about what you get (losing weight, publishing a book). Processes are about what you do (your workout routine, your writing schedule). Identity is about what you believe (your self-image, your worldview). Most people start with outcomes: "I want to lose 20 pounds." The more effective approach starts with identity: "I am the type of person who takes care of their body." Every action you take is a vote for the type of person you wish to become. No single instance will transform your beliefs, but as the votes build up, so does the evidence of your new identity. True behavior change is identity change. You might start a habit because of motivation, but you stick with it because it becomes part of who you are.', addedBy: 'system' },
      { bookId: atomicHabits.id, chapterNumber: 3, title: 'How to Build Better Habits in 4 Simple Steps', summary: 'The four laws of behavior change: cue, craving, response, and reward.', content: 'A habit is a behavior that has been repeated enough times to become automatic. The process of building a habit can be divided into four simple steps: cue, craving, response, and reward. The cue triggers your brain to initiate a behavior. The craving is the motivational force — you don\'t crave the habit itself but the change in state it delivers. The response is the actual habit you perform. The reward is the end goal. These four steps form a neurological feedback loop — cue, craving, response, reward — that ultimately allows you to create automatic habits. This cycle is known as the habit loop. The Four Laws of Behavior Change map to these steps: (1) Make it obvious (cue), (2) Make it attractive (craving), (3) Make it easy (response), (4) Make it satisfying (reward).', addedBy: 'system' },
      { bookId: atomicHabits.id, chapterNumber: 4, title: 'The Man Who Didn\'t Look Right', summary: 'How awareness and habit scorecards help you notice unconscious patterns.', content: 'The process of behavior change always starts with awareness. Before we can effectively build new habits, we need to get a handle on our current ones. Many of our failures in performance are largely attributable to a lack of self-awareness. A Habit Scorecard is a simple exercise: list your daily habits from morning to night and mark each one as positive (+), negative (-), or neutral (=). The point is not to judge yourself but to observe. The psychologist Carl Jung said, "Until you make the unconscious conscious, it will direct your life and you will call it fate." Pointing-and-Calling, a safety system used in Japanese railways, reduces errors by up to 85 percent by raising the level of awareness from an unconscious habit to a deliberate action.', addedBy: 'system' },
    );
  }

  if (allChapters.length > 0) {
    await chaptersStore.createMany(allChapters);
    console.log(`  Seeded ${allChapters.length} chapters across ${new Set(allChapters.map(c => c.bookId)).size} books`);
  }
}

module.exports = seed;
